export { default as PostCard} from '@/components/PostCard'
export { default as Categories} from '@/components/Categories'
export { default as PostWidget} from '@/components/PostWidget'
export { default as Header} from '@/components/Header'
export { default as Posts} from '@/components/Posts'
export { default as FeaturedPost} from '@/components/FeaturedPost'
export { default as FeaturedPostCard} from '@/components/FeaturedPostCard'
export {default as Author} from '@/components/postComponents/Author'
export {default as Comments} from '@/components/postComponents/Comments'
export {default as CommentsForm} from '@/components/postComponents/CommentsForm'
export {default as PostDetail} from '@/components/postComponents/PostDetail'

